language: python
python:
  - "3.6"
# Generate requirements.txt from your current python env: pip freeze > requirements.txt
#install:
#  - pip install -r requirements.txt
script:
  # This assumes all test files are named "something_test.py"
  - python -m unittest discover . "*_test.py"
